"""Shared pytest fixtures for AI Governance MCP Server tests.

Per governance framework Q3 (Testing Integration): Fixtures support test isolation
and reproducibility across unit, integration, and behavior tests.
"""

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import Mock

import numpy as np
import pytest

# Ensure src is in path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from ai_governance_mcp.models import (
    ConfidenceLevel,
    DomainConfig,
    DomainIndex,
    ErrorResponse,
    Feedback,
    GlobalIndex,
    Method,
    Metrics,
    Principle,
    PrincipleMetadata,
    QueryLog,
    ReferenceEntry,
    RetrievalResult,
    ScoredMethod,
    ScoredPrinciple,
    ScoredReference,
)
from ai_governance_mcp.config import Settings


# =============================================================================
# Home isolation — the test suite must not write to production telemetry
# =============================================================================


@pytest.fixture(autouse=True)
def isolate_home(request, tmp_path_factory, monkeypatch):
    """Point ``$HOME`` at a throwaway directory for every test.

    **Why this is autouse and global rather than per-call-site.** Six hooks in
    ``.claude/hooks/`` append to logs under ``$HOME``, and the hook tests invoke
    those hooks as real subprocesses. Isolation was therefore a choice made
    (or forgotten) at each of ~210 ``run_hook`` call sites spread across seven
    independent copies of a ``run_hook`` helper. It was forgotten most of the
    time, and the failure is silent: the test passes either way.

    Measured consequence before this fixture existed:
    ``~/.context-engine/plan-contrarian-denies.log`` held **872 lines, 865 of
    them generated by the test suite** — 7 real events buried in 99.2% noise.
    That log is the named instrument for OPERATIONS **V-012**, so a verification
    item was measuring its own test runs. The same class had already happened
    once, when a fixture overwrote the committed index with random vectors, so
    this is the second instance of "tests write to a production artifact" — a
    rule, not an incident.

    Fixing the call sites would leave the eighth copy of the helper free to
    reintroduce it. Fixing the environment removes the choice.

    **Blast radius, measured rather than assumed:** the full suite was run with
    ``HOME`` redirected before this shipped — 2710 passed, 2 failed, and both
    failures are tests that legitimately need the real home. Those two carry
    ``@pytest.mark.real_home``. If a third ever needs it, the marker is the
    honest way to say so; silently reading the real home is not.
    """
    if request.node.get_closest_marker("real_home"):
        return

    # PRESERVE READ ACCESS TO THE INDEX (session-268). This fixture exists to stop
    # tests WRITING to production telemetry under $HOME. The governance index is
    # read-only for tests — isolating it buys nothing and breaks every test that needs
    # one, because the index stopped being committed and now defaults to
    # `~/.ai-governance/index`. Symptom when this was missing: 14 tests failed on
    # `main` (but passed in the authoring worktree, which still had a leftover
    # `index/` on disk — the merge deleted it from `main`). Pin the real location
    # BEFORE $HOME moves, and only when the caller has not already chosen one.
    if not os.environ.get("AI_GOVERNANCE_INDEX_PATH"):
        real_index = (
            Path(
                os.environ.get("AI_GOVERNANCE_USER_DATA_ROOT", "~/.ai-governance")
            ).expanduser()
            / "index"
        )
        if (real_index / "global_index.json").is_file():
            monkeypatch.setenv("AI_GOVERNANCE_INDEX_PATH", str(real_index))

    home = tmp_path_factory.mktemp("home")
    (home / ".claude").mkdir(exist_ok=True)
    (home / ".context-engine").mkdir(exist_ok=True)
    monkeypatch.setenv("HOME", str(home))


# -- Reference-library write guard (#294) ------------------------------------


def _snapshot_dir(path: Path) -> dict[str, int]:
    """``{relative_posix_path: mtime_ns}`` for every file under *path*."""
    if not path.is_dir():
        return {}
    return {
        str(p.relative_to(path)): p.stat().st_mtime_ns
        for p in path.rglob("*")
        if p.is_file()
    }


def _diff_snapshots(before: dict[str, int], after: dict[str, int]) -> list[str]:
    """Paths that are new or modified in *after* relative to *before*."""
    return sorted(p for p, mtime in after.items() if before.get(p) != mtime)


@pytest.fixture(scope="session", autouse=True)
def _guard_real_reference_library():
    """Fail the run if ANY test writes to the REAL reference library.

    BACKLOG #294 defense-in-depth.  ``isolate_home`` is the primary guard
    (function-scoped, redirects ``$HOME``); this is the backstop that catches
    a regression — for instance a test that opts out via ``@pytest.mark.real_home``
    and then calls ``capture_reference``.

    The watched path is derived from the SAME resolution order as
    ``config._user_data_root()`` / ``Settings.reference_library_path``, using the
    pristine ambient env (session scope runs before any per-test monkeypatch).
    Hardcoding ``~/.ai-governance/reference-library/`` would reproduce the
    exact class of bug this guard exists to catch — two consumers resolving the
    path differently.
    """
    import pwd

    try:
        real_home = Path(pwd.getpwuid(os.getuid()).pw_dir).resolve()
    except KeyError:
        yield
        return

    ref_lib_override = os.environ.get("AI_GOVERNANCE_REFERENCE_LIBRARY_PATH")
    if ref_lib_override:
        ref_lib = Path(ref_lib_override).expanduser().resolve()
    else:
        data_root_override = os.environ.get("AI_GOVERNANCE_USER_DATA_ROOT")
        data_root = (
            Path(data_root_override).expanduser()
            if data_root_override
            else real_home / ".ai-governance"
        )
        ref_lib = data_root / "reference-library"

    before = _snapshot_dir(ref_lib)
    yield
    after = _snapshot_dir(ref_lib)
    changed = _diff_snapshots(before, after)
    assert not changed, (
        f"Test suite wrote to the REAL reference library at {ref_lib}: "
        f"{changed}.  A test bypassed isolate_home and wrote a reference-library "
        "entry.  See BACKLOG #294 / tests/test_home_isolation.py."
    )


# =============================================================================
# Environment Fixtures
# =============================================================================


@pytest.fixture(autouse=True)
def _disable_interactive_vcs_prompts(monkeypatch):
    """Keep Git and GitHub CLI subprocesses non-interactive during tests.

    The global HOME isolation fixture deliberately hides the user's credential
    helper configuration. A hook test that reaches a real HTTPS remote must
    fail promptly rather than block the suite waiting for credentials.
    """
    monkeypatch.setenv("GIT_TERMINAL_PROMPT", "0")
    monkeypatch.setenv("GH_PROMPT_DISABLED", "1")


@pytest.fixture(autouse=True)
def _disable_embedding_ipc(monkeypatch):
    """Force local SentenceTransformer path in tests.

    When a watcher daemon is running locally, EmbeddingClient.available()
    returns True and intercepts SentenceTransformer mock patches. Setting
    AI_CONTEXT_ENGINE_EMBED_SOCKET=none mirrors the daemon's self-loop guard
    and ensures mocks apply. CI has no daemon, so this is a no-op there.

    Opt-out: tests that need the real IPC path must override this fixture's
    effect in their own `monkeypatch` scope — either
    `monkeypatch.setenv("AI_CONTEXT_ENGINE_EMBED_SOCKET", "<real path>")`
    or `monkeypatch.delenv("AI_CONTEXT_ENGINE_EMBED_SOCKET", raising=False)`.
    (See test_embedding_ipc.py::test_env_var_outside_containment_rejected
    for an example that overrides this fixture.)
    """
    monkeypatch.setenv("AI_CONTEXT_ENGINE_EMBED_SOCKET", "none")


# =============================================================================
# Path Fixtures
# =============================================================================


@pytest.fixture
def temp_dir(tmp_path):
    """Temporary directory for test artifacts."""
    return tmp_path


@pytest.fixture
def test_settings(temp_dir):
    """Settings pointing to temporary directories for isolated tests."""
    settings = Settings()
    # Override paths to use temp directories
    settings.documents_path = temp_dir / "documents"
    settings.index_path = temp_dir / "index"
    settings.logs_path = temp_dir / "logs"
    # PIN THE LIBRARY INTO THE TEMP TREE (session-268). It is now its own setting whose
    # default is a USER-DATA path, so leaving it unset would point tests at the real
    # `~/.ai-governance/reference-library` — a capture test would write into the human's
    # actual library. Same class as the `plan-contrarian-denies.log` corruption
    # session-265 fixed environmentally: an unpinned path in a fixture writes to a live
    # instrument. Co-located with the corpus here, which is still a supported layout.
    settings.reference_library_path = temp_dir / "reference-library"

    # Create directories
    settings.documents_path.mkdir(parents=True)
    settings.index_path.mkdir(parents=True)
    settings.logs_path.mkdir(parents=True)

    # Disable keyword adjudicator by default — tests that specifically test
    # adjudication routing (TestKeywordAdjudicationRouting) set the mode
    # explicitly per test. Other tests that happen to trigger keywords should
    # not be affected by adjudicator availability (requires Codex).
    settings.keyword_judge_mode = "off"

    return settings


# =============================================================================
# Storage Fixtures
# =============================================================================


@pytest.fixture
def storage(tmp_path):
    """FilesystemStorage backed by a per-test temp directory.

    Consolidated from 4 byte-identical class-nested fixtures in
    test_context_engine.py (session-123 Phase 2). Module-level scope here
    means pytest auto-injects into any test method with a `storage` parameter.
    """
    from ai_governance_mcp.context_engine.storage.filesystem import FilesystemStorage

    return FilesystemStorage(base_path=tmp_path / "indexes")


# =============================================================================
# Model Fixtures - Principles
# =============================================================================


@pytest.fixture
def sample_principle():
    """Minimal valid Principle for unit tests."""
    return Principle(
        id="meta-C1",
        domain="constitution",
        series_code="C",
        number=1,
        title="Test Principle",
        content="This is test content for the principle. It contains enough text to be meaningful for testing purposes.",
        line_range=(1, 10),
        metadata=PrincipleMetadata(
            keywords=["test", "sample", "principle"],
            synonyms=["example"],
            trigger_phrases=["test scenario"],
            failure_indicators=["test failure"],
            aliases=["C1"],
        ),
        embedding_id=0,
    )


@pytest.fixture
def sample_s_series_principle():
    """S-Series safety principle for testing priority and triggering."""
    return Principle(
        id="meta-S1",
        domain="constitution",
        series_code="S",
        number=1,
        title="Safety First",
        content="Safety content that should always be prioritized. S-Series principles take precedence over all other series.",
        line_range=(1, 5),
        metadata=PrincipleMetadata(
            keywords=["safety", "priority", "harm"],
            trigger_phrases=["safety concern"],
            failure_indicators=["safety violation"],
        ),
        embedding_id=1,
    )


@pytest.fixture
def sample_quality_principle():
    """Q-Series quality principle for testing hierarchy."""
    return Principle(
        id="meta-Q1",
        domain="constitution",
        series_code="Q",
        number=1,
        title="Quality Standards",
        content="Quality standards for verification and testing.",
        line_range=(20, 30),
        metadata=PrincipleMetadata(keywords=["quality", "testing"]),
        embedding_id=2,
    )


@pytest.fixture
def sample_coding_principle():
    """Domain-specific principle for ai-coding domain."""
    return Principle(
        id="coding-C1",
        domain="ai-coding",
        series_code="C",
        number=1,
        title="Code Quality",
        content="Maintain high code quality standards in all implementations.",
        line_range=(10, 20),
        metadata=PrincipleMetadata(keywords=["code", "quality", "implementation"]),
        embedding_id=3,
    )


# =============================================================================
# Model Fixtures - Methods
# =============================================================================


@pytest.fixture
def sample_method():
    """Minimal valid Method for unit tests."""
    return Method(
        id="coding-M1",
        domain="ai-coding",
        title="Cold Start Kit",
        content="Method content describing the cold start procedure for new projects.",
        line_range=(100, 150),
        keywords=["cold", "start", "initialization"],
        # Must be the item's real row in `mock_embeddings` — retrieval maps
        # embedding rows to items by embedding_id, and an id outside the matrix
        # makes the whole index unmappable, silently degrading every engine
        # built on `saved_index` to BM25-only. See saved_index's bijection
        # assertion. (Was 10 against a 7-row matrix.)
        embedding_id=4,
    )


@pytest.fixture
def sample_method_2():
    """Second method for testing multiple methods."""
    return Method(
        id="coding-M2",
        domain="ai-coding",
        title="Gate Validation",
        content="Procedure for validating phase transition gates.",
        line_range=(160, 200),
        keywords=["gate", "validation", "phase"],
        embedding_id=5,  # real row in mock_embeddings (was 11)
    )


# =============================================================================
# Model Fixtures - Domain Configuration
# =============================================================================


@pytest.fixture
def sample_domain_config():
    """Minimal DomainConfig for constitution domain."""
    return DomainConfig(
        name="constitution",
        display_name="Constitution",
        principles_file="test-principles.md",
        methods_file=None,
        description="Universal behavioral rules for AI interaction.",
        priority=0,
        embedding_id=0,
    )


@pytest.fixture
def sample_coding_domain_config():
    """DomainConfig for ai-coding domain."""
    return DomainConfig(
        name="ai-coding",
        display_name="AI Coding",
        principles_file="test-coding-principles.md",
        methods_file="test-coding-methods.md",
        description="Software development with AI assistance.",
        priority=10,
        embedding_id=1,
    )


# =============================================================================
# Model Fixtures - Index Structures
# =============================================================================


@pytest.fixture
def sample_domain_index(
    sample_principle, sample_s_series_principle, sample_quality_principle
):
    """DomainIndex for constitution domain with multiple principles."""
    return DomainIndex(
        domain="constitution",
        principles=[
            sample_principle,
            sample_s_series_principle,
            sample_quality_principle,
        ],
        methods=[],
        last_extracted="2025-01-01T00:00:00Z",
        version="1.0",
    )


@pytest.fixture
def sample_reference_entry():
    """ReferenceEntry for ai-coding domain integration tests."""
    return ReferenceEntry(
        id="ref-ai-coding-test-integration-pattern",
        domain="ai-coding",
        title="Integration Test Setup Pattern",
        summary="Proven pattern for setting up integration tests with fixtures",
        content="Use pytest fixtures with tmp_path for isolated test environments...",
        tags=["testing", "integration", "fixtures"],
        status="current",
        maturity="evergreen",
        entry_type="direct",
        decay_class="framework",
        embedding_id=6,  # last row of mock_embeddings
    )


@pytest.fixture
def sample_coding_domain_index(
    sample_coding_principle, sample_method, sample_method_2, sample_reference_entry
):
    """DomainIndex for ai-coding domain with principles, methods, and references."""
    return DomainIndex(
        domain="ai-coding",
        principles=[sample_coding_principle],
        methods=[sample_method, sample_method_2],
        references=[sample_reference_entry],
        last_extracted="2025-01-01T00:00:00Z",
        version="1.0",
    )


@pytest.fixture
def sample_global_index(
    sample_domain_index,
    sample_coding_domain_index,
    sample_domain_config,
    sample_coding_domain_config,
):
    """GlobalIndex with two domains for integration tests."""
    return GlobalIndex(
        domains={
            "constitution": sample_domain_index,
            "ai-coding": sample_coding_domain_index,
        },
        domain_configs=[sample_domain_config, sample_coding_domain_config],
        created_at="2025-01-01T00:00:00Z",
        version="1.0",
        embedding_model="BAAI/bge-small-en-v1.5",
        embedding_dimensions=384,
    )


# =============================================================================
# Model Fixtures - Scored Results
# =============================================================================


@pytest.fixture
def scored_principle(sample_principle):
    """ScoredPrinciple with realistic scores for testing."""
    return ScoredPrinciple(
        principle=sample_principle,
        semantic_score=0.75,
        keyword_score=0.60,
        combined_score=0.69,
        rerank_score=0.72,
        confidence=ConfidenceLevel.MEDIUM,
        match_reasons=["strong semantic similarity", "keyword match: test"],
    )


@pytest.fixture
def scored_s_series(sample_s_series_principle):
    """Scored S-Series principle with high confidence."""
    return ScoredPrinciple(
        principle=sample_s_series_principle,
        semantic_score=0.85,
        keyword_score=0.70,
        combined_score=0.79,
        rerank_score=0.82,
        confidence=ConfidenceLevel.HIGH,
        match_reasons=["safety concern detected"],
    )


@pytest.fixture
def scored_method(sample_method):
    """ScoredMethod for testing method retrieval."""
    return ScoredMethod(
        method=sample_method,
        semantic_score=0.65,
        keyword_score=0.55,
        combined_score=0.61,
        confidence=ConfidenceLevel.MEDIUM,
    )


@pytest.fixture
def scored_reference():
    """ScoredReference for testing reference retrieval logging."""
    ref = ReferenceEntry(
        id="ref-ai-coding-test-pattern",
        domain="ai-coding",
        title="Test Pattern Reference",
        content="Sample reference content for testing.",
        tags=["testing", "patterns"],
        maturity="seedling",
    )
    return ScoredReference(
        reference=ref,
        semantic_score=0.70,
        keyword_score=0.60,
        combined_score=0.66,
        confidence=ConfidenceLevel.MEDIUM,
    )


@pytest.fixture
def sample_retrieval_result(
    scored_principle, scored_s_series, scored_method, scored_reference
):
    """Complete RetrievalResult for testing formatters and handlers."""
    return RetrievalResult(
        query="test query for governance",
        domains_detected=["constitution", "ai-coding"],
        domain_scores={"constitution": 0.85, "ai-coding": 0.72},
        constitution_principles=[scored_s_series, scored_principle],
        domain_principles=[],
        methods=[scored_method],
        references=[scored_reference],
        s_series_triggered=True,
        retrieval_time_ms=45.5,
    )


# =============================================================================
# Embedding Fixtures (Mocked)
# =============================================================================


@pytest.fixture
def mock_embeddings():
    """Mock content embeddings array (7 items, 384 dims).

    Matches BM25 doc count: 3 constitution principles + 1 coding principle
    + 2 methods + 1 reference = 7. Use deterministic random seed for
    reproducibility.
    """
    np.random.seed(42)
    return np.random.rand(7, 384).astype(np.float32)


@pytest.fixture
def mock_domain_embeddings():
    """Mock domain embeddings — one row per domain_config in sample_global_index.

    Row count MUST equal len(domain_configs). It was 3 against 2 configs, which
    the positional pairing tolerated but the BACKLOG #218 identity gate does not:
    row 2 was claimed by nobody, so the matrix was rejected and domain routing
    was silently off for every test using `saved_index`. Nothing failed, because
    the only routing assertions on this fixture are tautological. Pinned by an
    assertion in `saved_index` itself.
    """
    np.random.seed(43)
    return np.random.rand(2, 384).astype(np.float32)


@pytest.fixture
def mock_query_embedding():
    """Mock embedding for a query (384 dims)."""
    np.random.seed(44)
    return np.random.rand(384).astype(np.float32)


@pytest.fixture
def mock_embedder():
    """Mocked SentenceTransformer that returns consistent embeddings."""
    embedder = Mock()
    np.random.seed(45)

    def mock_encode(texts, *args, **kwargs):
        """Return embeddings matching input shape."""
        if isinstance(texts, str):
            return np.random.rand(384).astype(np.float32)
        return np.random.rand(len(texts), 384).astype(np.float32)

    embedder.encode = Mock(side_effect=mock_encode)
    embedder.get_sentence_embedding_dimension = Mock(return_value=384)
    return embedder


@pytest.fixture
def mock_reranker():
    """Mocked CrossEncoder that returns plausible rerank scores."""
    reranker = Mock()

    def mock_predict(pairs, *args, **kwargs):
        """Return scores matching input length."""
        if isinstance(pairs, list):
            return np.array([0.8 - i * 0.1 for i in range(len(pairs))])
        return np.array([0.5])

    reranker.predict = Mock(side_effect=mock_predict)
    return reranker


# =============================================================================
# File Fixtures - Test Documents
# =============================================================================


@pytest.fixture
def sample_principles_md(temp_dir):
    """Create a minimal principles markdown file for extraction testing."""
    content = """# Test Principles Document

## Series S: Safety

### S1. Safety First
**Definition**
Safety is paramount and must be considered in all decisions.

**How the AI Applies This Principle**
- Check for safety implications
- Escalate safety concerns immediately

## Series C: Core

### C1. Test Principle One
**Definition**
This is the first test principle with enough content to test extraction.

**How the AI Applies This Principle**
- Apply consistently
- Document everything

### C2. Test Principle Two
**Definition**
This is the second test principle.

**Failure Mode: Coverage Gaming**
Writing tests that exercise code but don't validate behavior.

## Series Q: Quality

### Q1. Quality Standards
**Definition**
Maintain quality in all outputs.
"""
    path = temp_dir / "documents" / "test-principles.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return path


@pytest.fixture
def sample_methods_md(temp_dir):
    """Create a minimal methods markdown file for extraction testing."""
    content = """# Test Methods Document

## 1 Cold Start Kit
Procedure for initializing new projects.

### Step 1
Create required files.

### Step 2
Run initial setup.

## 2 Gate Validation
Procedure for validating phase gates.

### Checklist
- [ ] All tests passing
- [ ] Coverage meets threshold
"""
    path = temp_dir / "documents" / "test-methods.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return path


@pytest.fixture
def sample_coding_principles_md(temp_dir):
    """Create a minimal AI coding principles markdown file for extraction testing."""
    content = """# AI Coding Domain Principles

## C1: Code Quality First

**Definition:** Prioritize maintainable, readable code.

All code must be well-tested and documented.

## C2: Test Coverage

**Definition:** Maintain adequate test coverage.

Tests should validate behavior, not just exercise code.
"""
    path = temp_dir / "documents" / "test-coding-principles.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return path


@pytest.fixture
def sample_domains_json(
    temp_dir, sample_principles_md, sample_coding_principles_md, sample_methods_md
):
    """Create a domains.json configuration file for testing."""
    domains = [
        {
            "name": "constitution",
            "display_name": "Constitution",
            "principles_file": "test-principles.md",
            "methods_file": None,
            "description": "Universal behavioral rules.",
            "priority": 0,
        },
        {
            "name": "ai-coding",
            "display_name": "AI Coding",
            "principles_file": "test-coding-principles.md",
            "methods_file": "test-methods.md",
            "description": "Software development with AI.",
            "priority": 10,
        },
    ]
    path = temp_dir / "documents" / "domains.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(domains, indent=2))
    return path


# =============================================================================
# Integration Fixtures - Saved Index
# =============================================================================


@pytest.fixture
def saved_index(
    test_settings, sample_global_index, mock_embeddings, mock_domain_embeddings
):
    """Save a complete index to disk for integration tests.

    Returns the settings pointing to the saved index.
    """
    # Guard the fixture's own invariant. Retrieval maps embedding rows to items
    # by `embedding_id` and discards the vectors entirely if those ids are not a
    # bijection onto the matrix rows — so a drifted id here would silently
    # degrade every engine built on this fixture to BM25-only, with most tests
    # still passing because their assertions do not require semantic results.
    # Fail loudly at the fixture instead. (This drifted once: two methods
    # carried ids 10/11 against a 7-row matrix, and a reference carried none.)
    ids = sorted(
        item.embedding_id
        for domain in sample_global_index.domains.values()
        for item in (*domain.principles, *domain.methods, *domain.references)
    )
    assert ids == list(range(len(mock_embeddings))), (
        f"fixture embedding_ids {ids} are not a bijection onto "
        f"[0, {len(mock_embeddings)}) — semantic search would be silently "
        "disabled for every test using saved_index"
    )

    # Same check for the DOMAIN matrix. The content-side assertion existed and
    # the domain-side one did not, which is the "fixed one consumer, missed the
    # other" pattern the shared `_slot_assign` validator was written to prevent
    # — so the fixture guards both consumers or it guards neither.
    domain_ids = sorted(
        dc.embedding_id
        for dc in sample_global_index.domain_configs
        if dc.embedding_id is not None
    )
    assert domain_ids == list(range(len(mock_domain_embeddings))), (
        f"fixture domain embedding_ids {domain_ids} are not a bijection onto "
        f"[0, {len(mock_domain_embeddings)}) — domain routing would be silently "
        "disabled for every test using saved_index"
    )

    # Save JSON index
    index_file = test_settings.index_path / "global_index.json"
    with open(index_file, "w") as f:
        json.dump(sample_global_index.model_dump(), f)

    # Save embeddings
    np.save(test_settings.index_path / "content_embeddings.npy", mock_embeddings)
    np.save(test_settings.index_path / "domain_embeddings.npy", mock_domain_embeddings)

    return test_settings


# =============================================================================
# Server State Fixtures
# =============================================================================


@pytest.fixture
def reset_server_state():
    """Reset global server state before and after each test.

    Critical for server tests to ensure test isolation.
    State variables live in _state module (including _cached_roots_path);
    deques in _logging; rate-limit in _security.

    Also clears the two PROCESS-LIFETIME latches introduced with the durable-write
    guard: the telemetry failure counters and the once-per-process "data root not
    found" flag. Both are deliberately sticky in production (they exist to stop a
    per-call warning storm), which makes them cross-test contamination in here —
    a test asserting "exactly one warning" or "exactly one counted failure" would
    pass or fail on test ORDER. Found by cross-vendor review.
    """
    from ai_governance_mcp import config
    from ai_governance_mcp.server import _logging, _security, _state
    from ai_governance_mcp.server._logging import _audit_log, _reasoning_log

    def _reset() -> None:
        _state.reset()
        _audit_log.clear()
        _reasoning_log.clear()
        _logging._telemetry_failures.clear()
        config._ROOT_WARNING_EMITTED = False
        _security._rate_limit_tokens = _security.RATE_LIMIT_TOKENS

    _reset()
    yield
    _reset()


@pytest.fixture
def sample_metrics():
    """Pre-populated Metrics for testing metrics endpoints."""
    return Metrics(
        total_queries=100,
        avg_retrieval_time_ms=45.2,
        s_series_trigger_count=15,
        domain_query_counts={"constitution": 100, "ai-coding": 75, "multi-agent": 25},
        confidence_distribution={"high": 30, "medium": 50, "low": 20},
        feedback_count=10,
        avg_feedback_rating=4.2,
    )


@pytest.fixture
def sample_query_log():
    """Sample QueryLog for testing logging functions."""
    return QueryLog(
        timestamp=datetime.now(timezone.utc).isoformat(),
        query="test query",
        domains_detected=["constitution", "ai-coding"],
        principles_returned=["meta-C1", "coding-C1"],
        methods_returned=["coding-M1"],
        references_returned=["ref-ai-coding-test-pattern"],
        s_series_triggered=False,
        retrieval_time_ms=42.5,
        top_confidence=ConfidenceLevel.HIGH,
    )


@pytest.fixture
def sample_feedback():
    """Sample Feedback for testing feedback logging."""
    return Feedback(
        query="test query",
        principle_id="meta-C1",
        rating=4,
        comment="Helpful result",
        timestamp=datetime.now(timezone.utc).isoformat(),
        session_id="test-session-123",
    )


# =============================================================================
# Real Index Fixtures (for @pytest.mark.real_index tests)
# =============================================================================


@pytest.fixture
def real_index_path():
    """Path to the production index for real integration tests.

    Only used with @pytest.mark.real_index decorator.

    **Resolve, do not hardcode.** This used to return ``project_root / "index"``.
    The index moved out of the checkout in session-268, so that path became an
    empty directory in the primary and absent in every worktree — and because the
    miss is expressed as ``pytest.skip``, the whole ``real_index`` class went
    quiet instead of red. Measured 2026-08-10 before this fix:
    ``pytest tests/test_retrieval_quality.py`` reported **14 skipped, 0 run** —
    the entire MRR / Recall@10 / Precision@5 benchmark had not executed since the
    move, which is also why session-300 recorded the post-rebuild retrieval
    baseline as "unmeasured".

    ``isolate_home`` (autouse, above) already pins ``AI_GOVERNANCE_INDEX_PATH`` to
    the real user-data index *before* it moves ``$HOME``, so ``Settings()`` resolves
    correctly inside a test. Use that. The repo-local path stays as a fallback for
    grandfathered checkouts that still keep an index in-tree.

    The sibling fields in ``real_settings`` below carry comments explaining that
    logs and the reference library moved out of the checkout and must not be
    hardcoded. The same reasoning always applied here; it was simply never applied.
    A skip is not a pass — a fixture that can only skip is a test that does not exist.
    """
    from tests.index_paths import (
        index_not_built_reason,
        index_staleness_reason,
        resolve_index_dir,
    )

    index_dir = resolve_index_dir()
    if index_dir is None:
        pytest.skip(index_not_built_reason())
    stale = index_staleness_reason(index_dir)
    if stale:
        pytest.skip(stale)
    return index_dir


@pytest.fixture
def real_settings(real_index_path):
    """Settings pointing to real production index."""
    project_root = Path(__file__).parent.parent
    settings = Settings()
    settings.documents_path = project_root / "documents"
    settings.index_path = real_index_path
    # `logs_path` deliberately NOT overridden — same reason as the library below. It
    # moved out of the checkout at Compliance Review #17 (BACKLOG #261); a hardcoded
    # `project_root / "logs"` would point this fixture at a directory the server no
    # longer writes, and in a worktree it would name a per-worktree tree that is exactly
    # the fragmentation #261 removed.
    # Env-aware: the library moved out of the checkout (session-268), so a hardcoded
    # `project_root / "reference-library"` would now name a directory that does not
    # exist. Settings() already resolved it from AI_GOVERNANCE_REFERENCE_LIBRARY_PATH or
    # the user-data default; leave that alone rather than overriding it with a stale path.
    return settings


# =============================================================================
# Utility Fixtures
# =============================================================================


@pytest.fixture
def iso_timestamp():
    """Generate a valid ISO timestamp for testing."""
    return datetime.now(timezone.utc).isoformat()


@pytest.fixture
def sample_error_response():
    """Sample ErrorResponse for testing error handling."""
    return ErrorResponse(
        error_code="PRINCIPLE_NOT_FOUND",
        message="Principle 'meta-X99' not found",
        suggestions=["Try 'meta-C1'", "Use list_domains to see available principles"],
    )


# =============================================================================
# Unregistered-skip gate (session-302)
# =============================================================================
#
# Makes ONE observation structural instead of advisory: a skip must be registered.
# See tests/skip_allowlist.py for the root-cause reasoning and, importantly, for
# what this does NOT catch.
#
# Implemented as a session hook rather than a test because a test cannot observe
# the outcomes of the run that contains it.

_UNREGISTERED_SKIPS: list[tuple[str, str]] = []


def pytest_runtest_logreport(report):
    """Collect skip reasons as they occur.

    EXCLUDES xfail. pytest reports an xfailed test as ``outcome == "skipped"``
    with a ``wasxfail`` attribute set (verified by isolated repro: phase=call,
    ``hasattr(report, "wasxfail") is True``), so a bare ``report.skipped`` test
    swept up every xfail and failed the run for the opposite of this gate's
    purpose. Measured cost of the omission: ``pytest tests/test_doc_pointer_resolution.py``
    exited 1 with 5 passed / 1 xfailed / **zero real skips**, printing a
    misleading UNREGISTERED SKIPS banner — and the xfail in question is BACKLOG
    #325's acceptance test, so the arc's own completion proof returned red for a
    bogus reason. It went unseen because the standard command is
    ``pytest -m 'not slow'`` and that test is ``slow``, so no xfail ever reached
    this hook in a gate run.

    The distinction is the whole point: a **skip** asserts nothing and looks like
    success, which is what this gate exists to catch. An **xfail** is a declared,
    reviewed expected failure, and ``strict=True`` already fails the run if it
    starts passing — a stronger version of this same discipline, not a hole in it.
    """
    if report.skipped and not hasattr(report, "wasxfail"):
        reason = ""
        if isinstance(report.longrepr, tuple) and len(report.longrepr) == 3:
            reason = report.longrepr[2]
        else:
            reason = str(report.longrepr)
        from tests.skip_allowlist import is_registered

        if not is_registered(reason):
            _UNREGISTERED_SKIPS.append((report.nodeid, reason))


def pytest_sessionfinish(session, exitstatus):
    """Fail the run on any unregistered skip.

    A skip is the one outcome that looks like success and asserts nothing. Left
    advisory, a new one hides indefinitely — measured in session-302, where a
    stale hardcoded path silently skipped the entire retrieval benchmark for weeks
    while the suite reported green, and a guard added to fix that introduced a
    second silent-skip class the same day.
    """
    if not _UNREGISTERED_SKIPS:
        return
    print("\n\nUNREGISTERED SKIPS — a skip must be registered with a reason:")
    for nodeid, reason in _UNREGISTERED_SKIPS:
        print(f"  {nodeid}\n    {reason.strip()[:200]}")
    print(
        "\nIf the skip is correct, add an entry to tests/skip_allowlist.py saying "
        "WHY it is correct. If it is not correct, you have found a defect that "
        "would otherwise have been invisible in a green run."
    )
    session.exitstatus = 1
