"""The test suite must not write to production telemetry.

Guard for a defect class observed twice:

1. A fixture overwrote the committed embedding index with random vectors on
   every full-suite run (OPERATIONS, 2026-06).
2. ``~/.context-engine/plan-contrarian-denies.log`` accumulated **872 lines, 865
   of them generated by this test suite** — the hook tests invoke the real
   ``pre-exit-plan-mode-gate.sh`` as a subprocess, and it appends to
   ``$HOME/.context-engine/``. Only 7 entries were real.

The second is the expensive one: that log is the *named instrument* for
OPERATIONS **V-012** (Opus 5 unprompted-verification rate, thresholds CONFIRM
≤40% / REFUTE ≥60%). A verification item was measuring its own test runs at a
124:1 noise ratio.

Two instances make it a class, so the fix is environmental —
``conftest.isolate_home`` redirects ``$HOME`` for every test — and this file is
the probe proving the fix is live. Without it the fixture could be deleted and
every test would still pass, which is the exact failure mode under guard.

**Getting the real home is the subtle part.** ``os.path.expanduser("~")`` and
``Path.home()`` both *read* ``$HOME``, so under this fixture they return the
sandbox and any comparison against them is vacuous. The first draft of this file
did that and passed for the wrong reason. ``pwd.getpwuid`` reads the password
database instead, which the fixture cannot move.
"""

import os
import pwd
import subprocess
import sys
from pathlib import Path

import pytest

PROJECT_DIR = Path(__file__).parent.parent


def _real_home() -> Path:
    """The account's home, independent of ``$HOME``.

    Deliberately NOT ``Path.home()`` / ``expanduser`` — both consult ``$HOME``,
    which is the variable under test.

    Skips rather than errors when the UID has no passwd entry (e.g. containerised
    CI runners). An unavailable check must not masquerade as a failing one.
    """
    try:
        return Path(pwd.getpwuid(os.getuid()).pw_dir).resolve()
    except KeyError:  # pragma: no cover - container-only path
        pytest.skip("uid has no passwd entry (containerised run)")


def test_home_is_redirected_away_from_the_real_home():
    """The autouse fixture is active. Deleting it must fail here, loudly."""
    assert Path.home().resolve() != _real_home(), (
        f"HOME resolves to the real home ({_real_home()}) during tests. The "
        "conftest.isolate_home fixture is missing or disabled — hook subprocesses "
        "will append to production telemetry."
    )


def test_vcs_subprocesses_cannot_prompt_for_credentials(
    _disable_interactive_vcs_prompts,
):
    """Git and GitHub CLI prompt guards reach subprocesses, not just pytest."""
    result = subprocess.run(
        [
            sys.executable,
            "-c",
            (
                "import os; "
                "print(os.environ.get('GIT_TERMINAL_PROMPT')); "
                "print(os.environ.get('GH_PROMPT_DISABLED'))"
            ),
        ],
        capture_output=True,
        text=True,
        check=True,
        timeout=10,
    )
    assert result.stdout.splitlines() == ["0", "1"]


def test_hook_subprocess_write_lands_in_the_sandbox_not_the_real_log():
    """End-to-end: run a real logging hook, prove the append is contained.

    The test above proves the fixture set the variable. This proves the thing
    that actually matters — that a *subprocess*, which inherits the environment
    rather than the fixture, writes inside the sandbox. That distinction is the
    whole defect: the fixture is Python-side, the damage was shell-side.
    """
    hook = PROJECT_DIR / ".claude" / "hooks" / "pre-exit-plan-mode-gate.sh"
    if not hook.is_file():
        pytest.skip("hook not present in this checkout")

    real_log = _real_home() / ".context-engine" / "plan-contrarian-denies.log"
    real_before = real_log.read_text() if real_log.exists() else None

    sandbox_log = (
        Path(os.environ["HOME"]) / ".context-engine" / "plan-contrarian-denies.log"
    )
    assert sandbox_log != real_log, "sandbox and real log paths coincide"

    subprocess.run(
        ["bash", str(hook)],
        input='{"tool_name":"ExitPlanMode","tool_input":{}}',
        capture_output=True,
        text=True,
        timeout=30,
    )

    # POSITIVE assertion first: prove the hook actually ran and appended. Without
    # it, a hook that aborts on line 1 — or a missing `bash` — passes this test by
    # doing nothing, which is the vacuous-guard failure this file exists to catch.
    assert sandbox_log.exists(), (
        "the hook produced no log at all inside the sandbox — it did not run, so "
        "'the real log is untouched' proves nothing"
    )
    assert "deny" in sandbox_log.read_text(), (
        "the sandbox log exists but holds no deny record — the hook ran without "
        "reaching its audit path"
    )

    real_after = real_log.read_text() if real_log.exists() else None
    assert real_after == real_before, (
        f"A hook subprocess appended to the PRODUCTION log at {real_log}. "
        "HOME isolation is not reaching subprocesses — V-012's instrument is "
        "being corrupted by the test suite again."
    )
